#!/usr/bin/env bash
# mini swww wallpaper switcher with color support for waybar
# Made by Vodkaa (github.com/vodkaa-gal)
wall_dir="$HOME/Pictures/wallpapers"
wall_list=("$wall_dir"/*)

function chgwall_help {

printf "◤◢◤ CHANGEWALL USAGE ◢◤◢
changewall (i|n|p|s) [IMAGE_PATH]

i - init
n - next wallpaper
p - previous wallpaper
s - specify image\n"

}

function init {
	xtrans="grow"
	swww-daemon --format xrgb & disown
	sleep 1
}

function get_image {
	current=$(swww query | awk -F 'image: ' '{print $2}')

	if [ $order -eq 1 ]; then # reverse order if set to previous
		wall_list=( $(printf '%s\n' "${wall_list[@]}" | tac) )
	fi
	
	final=0
	
	for entry in "${wall_list[@]}" 
	do
		if [ -f $entry ]; then # ignore directories
			if [ $final == 1 ] # break if after current wallpaper
			then
				wall=$entry; break; 
			fi
	
			if [ "$entry" == "$current" ]
			then
				final=1 # set pass checkpoint
			fi
		fi
	done
	
	if [ ! -f "$wall" ]; then # set to first file if next file does not exist
		wall=$wall_list
	fi
}

function set_wall {
	if [ ! -f "$wall" ]; then # check if wall exists
		printf "No file specified. \n"
		exit
	fi

	colorz "$wall" --no-preview | \
	awk '{print "@define-color color"NR" "$1";"}' \
	> $HOME/.config/waybar/walcolors.css


	swww img "$wall" \
	--transition-bezier .43,1.19,1,.4 \
    	--transition-type grow \
    	--transition-duration 0.3 \
    	--transition-fps 60 \
    	--invert-y \
    	--transition-pos "$( hyprctl cursorpos )"

	pkill waybar
	waybar & disown
}

case $1 in
	h|-h|help|--help)
		chgwall_help
		;;
	i)
		init
		exit
		;;
	n)
		order=0
		get_image
		;;
	p)
		order=1
		get_image
		;;
	s)
		wall=$2
		;;
	*)
		chgwall_help
		printf "\nErr: Incorrect usage.\n"
		exit 1
		;;
esac

set_wall
