#!/usr/bin/env bash
db1="$1"
db2="$2"
db_name="$3"

if [ ! -f "$db1" ] || [ ! -f "$db2" ]; then 
	printf "file does not exist\n"
	exit 66; 
fi

merge_status=$(notify-send "Password required for merge." -a "$db_name" --action=1='Enter Password' --action=0='Ignore Merge')

if [ $merge_status -eq 1 ]; then
	pass=$(zenity --entry --text='Enter Password' --hide-text);
	key=$(zenity --file-selection);
	echo $pass
	echo $key
	cp "$db1" "$db1".bak && keepassxc-cli merge -s -k "$key" $db1 $db2 <<< "$pass";
	cp "$db2" "$db2".bak && keepassxc-cli merge -s -k "$key" $db2 $db1 <<< "$pass";
	pass='gay'
fi
